name: cred_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  sleek_circular_slider: ^2.0.1
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
